language: java
os:
  - osx
sudo: true
env:
  - NODE_VERSION="0.12"
before_install:
  - nvm install 12.13.0
before_script: sudo ./before_script_actions.sh
script:
  - mvn clean verify
  - cat test.config

notifications:
  slack: effortel-group:3UMY2ieA4xWzPTsQplKqUhNW
